import { NextResponse } from "next/server";
import OpenAI from "openai";

type BrainstormInput = {
  storyPillar?: string;
  themeCluster?: string;
  niche?: string;
  marketSignal?: string;
  targetAudience?: string;
  visualStyle?: string;
  language?: string;
  ideaCount?: number;
};

type GeneratedIdea = {
  title: string;
  theme: string;
  hook: string;
  thumbnail_prompt: string;
  storyline: string;
  notes: string;
  score: number;
  story_pillar: string;
  theme_cluster: string;
  niche: string;
  idea_angle: string;
  idea_formula: string;
  source_type: string;
  source_signal: string;
  priority_level: string;
  parent_path: string;
};

function cleanText(value: unknown, fallback: string) {
  const text = String(value || "").trim();

  return text || fallback;
}

function clampCount(value: unknown) {
  const numberValue = Number(value || 8);

  if (!Number.isFinite(numberValue)) return 8;

  return Math.min(15, Math.max(3, Math.round(numberValue)));
}

function getPriority(score: number) {
  if (score >= 92) return "Focus";
  if (score >= 82) return "Test";

  return "Backlog";
}

function pick<T>(items: T[], index: number) {
  return items[index % items.length];
}

function normalizeIdea(
  raw: Partial<GeneratedIdea>,
  input: Required<BrainstormInput>,
  index: number
): GeneratedIdea {
  const score = Number(raw.score || 86 + (index % 9));

  const title = cleanText(
    raw.title,
    `${input.niche} ${input.marketSignal} Story #${index + 1}`
  );

  const themeCluster = cleanText(raw.theme_cluster, input.themeCluster);
  const niche = cleanText(raw.niche, input.niche);
  const storyPillar = cleanText(raw.story_pillar, input.storyPillar);

  return {
    title,
    theme: cleanText(raw.theme, themeCluster),
    hook: cleanText(
      raw.hook,
      `Open with a strong contrast inside ${niche}, then reveal the ${input.marketSignal} twist in the first 10 seconds.`
    ),
    thumbnail_prompt: cleanText(
      raw.thumbnail_prompt,
      `High-contrast YouTube thumbnail for "${title}". Use expressive faces, clear transformation, bright colors, strong before-after composition, and do not copy any competitor thumbnail.`
    ),
    storyline: cleanText(
      raw.storyline,
      `A fresh original story based on ${themeCluster} → ${niche}. The story should use ${input.marketSignal} as a market signal, but rebuild new characters, new conflict, and a stronger emotional payoff.`
    ),
    notes: cleanText(
      raw.notes,
      `Generated by Brainstorm Flow V2. Target audience: ${input.targetAudience}. Visual style: ${input.visualStyle}.`
    ),
    score,
    story_pillar: storyPillar,
    theme_cluster: themeCluster,
    niche,
    idea_angle: cleanText(raw.idea_angle, input.marketSignal),
    idea_formula: cleanText(
      raw.idea_formula,
      `${themeCluster} + ${niche} + ${input.marketSignal} + Transformation Payoff`
    ),
    source_type: "Brainstorm Flow V2",
    source_signal: cleanText(raw.source_signal, input.marketSignal),
    priority_level: cleanText(raw.priority_level, getPriority(score)),
    parent_path: `${storyPillar} / ${themeCluster} / ${niche}`,
  };
}

function buildMockIdeas(input: Required<BrainstormInput>) {
  const count = clampCount(input.ideaCount);

  const settings = [
    "Fashion Contest",
    "School Competition",
    "Royal Family",
    "Secret Party",
    "Talent Show",
    "Ballet Contest",
    "K-pop Stage",
    "Mermaid Kingdom",
    "Rich Family Mansion",
    "Magic Academy",
  ];

  const conflicts = [
    "Poor Girl vs Rich Girl",
    "Broken Doll vs Perfect Doll",
    "Ignored Sister vs Golden Sister",
    "Fake Friend vs Real Friend",
    "Secret Princess vs Mean Queen",
    "Bullied Student vs Popular Girl",
    "Mermaid Girl vs Human Girl",
    "Giga Rich Family vs Poor Family",
  ];

  const payoffs = [
    "becomes the final winner",
    "reveals her hidden identity",
    "gets a dramatic makeover",
    "wins the rich family challenge",
    "turns the humiliation into power",
    "shocks everyone with her transformation",
    "becomes the queen of the contest",
    "proves she was the real star all along",
  ];

  const ideas: GeneratedIdea[] = [];

  for (let index = 0; index < count; index += 1) {
    const setting = pick(settings, index);
    const conflict = pick(conflicts, index);
    const payoff = pick(payoffs, index);
    const score = 88 + (index % 10);

    let title = `${input.niche} ${input.marketSignal} in ${setting}`;

    if (input.themeCluster.toLowerCase().includes("poor")) {
      title = `${conflict} ${input.marketSignal} in ${setting}`;
    }

    if (input.themeCluster.toLowerCase().includes("makeover")) {
      title = `${input.marketSignal} Makeover: From Invisible Girl to ${setting} Queen`;
    }

    if (input.themeCluster.toLowerCase().includes("adopt")) {
      title = `Poor Girl Adopted by ${input.marketSignal} Family in ${setting}`;
    }

    if (input.themeCluster.toLowerCase().includes("demon")) {
      title = `${input.marketSignal} Girl Hides Her Power at ${setting}`;
    }

    ideas.push(
      normalizeIdea(
        {
          title,
          theme: input.themeCluster,
          hook: `${conflict} is humiliated in ${setting}, but a ${input.marketSignal} twist changes the power dynamic immediately.`,
          thumbnail_prompt: `Split-screen thumbnail: left side shows ${conflict.toLowerCase()} before the twist, right side shows the shocking ${input.marketSignal} transformation in ${setting}. Bright colors, expressive faces, readable visual contrast.`,
          storyline: `Start with ${conflict} being underestimated. Put the character inside ${setting}. Use ${input.marketSignal} as the market signal, then create a fresh twist where she ${payoff}. End with a clear before-after emotional payoff.`,
          notes: `Flow: ${input.storyPillar} → ${input.themeCluster} → ${input.niche}. Market signal: ${input.marketSignal}. This is an original remix direction, not a copy.`,
          idea_angle: `${input.marketSignal} in ${setting}`,
          idea_formula: `${input.themeCluster} + ${input.niche} + ${setting} + ${payoff}`,
          score,
        },
        input,
        index
      )
    );
  }

  return ideas;
}

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as BrainstormInput;

    const input: Required<BrainstormInput> = {
      storyPillar: cleanText(body.storyPillar, "Story"),
      themeCluster: cleanText(body.themeCluster, "Poor vs Rich"),
      niche: cleanText(body.niche, "Poor vs Rich vs Giga Rich"),
      marketSignal: cleanText(body.marketSignal, "Huntrix Fashion Contest"),
      targetAudience: cleanText(body.targetAudience, "US kids and family audience"),
      visualStyle: cleanText(body.visualStyle, "bright contrast, transformation, expressive faces"),
      language: cleanText(body.language, "EN"),
      ideaCount: clampCount(body.ideaCount),
    };

    const mockMode = process.env.OPENAI_MOCK_MODE === "true";
    const apiKey = process.env.OPENAI_API_KEY;

    if (mockMode || !apiKey) {
      return NextResponse.json({
        mode: "mock",
        warning: mockMode
          ? "Mock mode is on."
          : "No OpenAI API key found. Returned mock brainstorm ideas.",
        ideas: buildMockIdeas(input),
      });
    }

    try {
      const openai = new OpenAI({
        apiKey,
      });

      const model = process.env.OPENAI_MODEL || "gpt-4o-mini";

      const response = await openai.chat.completions.create({
        model,
        response_format: {
          type: "json_object",
        },
        messages: [
          {
            role: "system",
            content:
              "You are StudioOS Brainstorm Flow V2. Generate original YouTube story ideas using a strict creative taxonomy. Never copy competitor titles. Always output valid JSON only.",
          },
          {
            role: "user",
            content: JSON.stringify({
              task: "Generate structured YouTube story ideas.",
              required_json_shape: {
                ideas: [
                  {
                    title: "string",
                    theme: "string",
                    hook: "string",
                    thumbnail_prompt: "string",
                    storyline: "string",
                    notes: "string",
                    score: "number 0-100",
                    story_pillar: "string",
                    theme_cluster: "string",
                    niche: "string",
                    idea_angle: "string",
                    idea_formula: "string",
                    source_signal: "string",
                    priority_level: "Focus | Test | Backlog",
                  },
                ],
              },
              rules: [
                "Follow this hierarchy: Story Pillar → Theme Cluster → Niche → Specific Idea.",
                "Use the market signal as inspiration, not as direct copying.",
                "Each title must be specific and clickable.",
                "Each idea must have a different setting or conflict.",
                "Thumbnail prompt must be visual and production-ready.",
                "Storyline must include setup, conflict, twist, payoff.",
              ],
              input,
            }),
          },
        ],
      });

      const content = response.choices[0]?.message?.content || "{}";
      const parsed = JSON.parse(content) as {
        ideas?: Partial<GeneratedIdea>[];
      };

      const ideas = (parsed.ideas || [])
        .slice(0, input.ideaCount)
        .map((idea, index) => normalizeIdea(idea, input, index));

      if (ideas.length === 0) {
        return NextResponse.json({
          mode: "fallback",
          warning: "OpenAI returned no usable ideas. Returned mock ideas.",
          ideas: buildMockIdeas(input),
        });
      }

      return NextResponse.json({
        mode: "openai",
        ideas,
      });
    } catch (error) {
      return NextResponse.json({
        mode: "fallback",
        warning:
          error instanceof Error
            ? error.message
            : "OpenAI generation failed. Returned mock ideas.",
        ideas: buildMockIdeas(input),
      });
    }
  } catch (error) {
    return NextResponse.json(
      {
        error:
          error instanceof Error
            ? error.message
            : "Invalid brainstorm request.",
      },
      {
        status: 400,
      }
    );
  }
}
