import { NextResponse } from "next/server";
import OpenAI from "openai";

type RemixInput = {
  storyPillar?: string;
  themeCluster?: string;
  niche?: string;
  marketSignal?: string;
  sourceTitle?: string;
  sourceDescription?: string;
  sourceChannel?: string;
  sourceUrl?: string;
  remixGoal?: string;
  remixRule?: string;
  targetAudience?: string;
  visualStyle?: string;
  language?: string;
  ideaCount?: number;
};

type RemixIdea = {
  title: string;
  theme: string;
  hook: string;
  thumbnail_prompt: string;
  storyline: string;
  notes: string;
  score: number;
  story_pillar: string;
  theme_cluster: string;
  niche: string;
  idea_angle: string;
  idea_formula: string;
  source_type: string;
  source_signal: string;
  priority_level: string;
  parent_path: string;
  remix_rule: string;
  remix_strategy: string;
};

function cleanText(value: unknown, fallback: string) {
  const text = String(value || "").trim();

  return text || fallback;
}

function clampCount(value: unknown) {
  const numberValue = Number(value || 6);

  if (!Number.isFinite(numberValue)) return 6;

  return Math.min(12, Math.max(3, Math.round(numberValue)));
}

function getPriority(score: number) {
  if (score >= 92) return "Focus";
  if (score >= 82) return "Test";

  return "Backlog";
}

function normalizeIdea(
  raw: Partial<RemixIdea>,
  input: Required<RemixInput>,
  index: number
): RemixIdea {
  const score = Number(raw.score || 88 + (index % 10));

  const title = cleanText(
    raw.title,
    `${input.niche} ${input.marketSignal} Original Remix #${index + 1}`
  );

  const storyPillar = cleanText(raw.story_pillar, input.storyPillar);
  const themeCluster = cleanText(raw.theme_cluster, input.themeCluster);
  const niche = cleanText(raw.niche, input.niche);

  return {
    title,
    theme: cleanText(raw.theme, themeCluster),
    hook: cleanText(
      raw.hook,
      `Use the source signal, but open with a new conflict in ${niche} and reveal a fresh ${input.marketSignal} twist.`
    ),
    thumbnail_prompt: cleanText(
      raw.thumbnail_prompt,
      `Create an original thumbnail inspired by the source signal "${input.marketSignal}". Do not copy the source. Use new characters, new setting, bright contrast, expressive faces, before-after composition and a clear transformation moment.`
    ),
    storyline: cleanText(
      raw.storyline,
      `Original remix based on ${storyPillar} → ${themeCluster} → ${niche}. Keep only the market logic from the source, then rebuild with new characters, new setting, new conflict and new payoff.`
    ),
    notes: cleanText(
      raw.notes,
      `Generated by Remix Rule Engine V2. Source: ${input.sourceTitle}. Rule: ${input.remixRule}.`
    ),
    score,
    story_pillar: storyPillar,
    theme_cluster: themeCluster,
    niche,
    idea_angle: cleanText(raw.idea_angle, input.marketSignal),
    idea_formula: cleanText(
      raw.idea_formula,
      `${themeCluster} + ${niche} + ${input.marketSignal} + New Setting + New Payoff`
    ),
    source_type: "Remix Rule Engine V2",
    source_signal: cleanText(raw.source_signal, input.marketSignal),
    priority_level: cleanText(raw.priority_level, getPriority(score)),
    parent_path: `${storyPillar} / ${themeCluster} / ${niche}`,
    remix_rule: cleanText(raw.remix_rule, input.remixRule),
    remix_strategy: cleanText(
      raw.remix_strategy,
      `Keep the winning market pattern, change characters, setting, conflict, twist and payoff.`
    ),
  };
}

function buildMockIdeas(input: Required<RemixInput>) {
  const settings = [
    "Fashion Contest",
    "Secret School Party",
    "Royal Family Challenge",
    "K-pop Stage Battle",
    "Rich Family Mansion",
    "Ballet Competition",
    "Mermaid Kingdom",
    "Magic Academy",
    "Talent Show Finale",
    "Princess Ceremony",
  ];

  const swaps = [
    "switch the social status",
    "change the final contest",
    "replace the family conflict",
    "make the hidden identity stronger",
    "turn the humiliation into transformation",
    "change the rival character",
    "make the ending more emotional",
    "add a public reveal moment",
  ];

  return Array.from({ length: input.ideaCount }).map((_, index) => {
    const setting = settings[index % settings.length];
    const swap = swaps[index % swaps.length];

    const score = 88 + (index % 10);

    const title = `${input.niche} ${input.marketSignal} Remix in ${setting}`;

    return normalizeIdea(
      {
        title,
        theme: input.themeCluster,
        hook: `A familiar source pattern is rebuilt in ${setting}, but the twist ${swap} so the audience feels it is new.`,
        thumbnail_prompt: `Original thumbnail for "${title}". Use a split-screen before-after layout, new characters, new costumes, expressive shocked faces, bright color contrast and a clear ${input.marketSignal} visual cue. Do not copy the source thumbnail.`,
        storyline: `Take the source signal "${input.sourceTitle}" only as a market pattern. Move it into ${setting}. Change the main character, rival, conflict and final reveal. Use ${input.marketSignal} as the new hook. The ending should deliver a stronger transformation payoff.`,
        notes: `Source channel: ${input.sourceChannel}. Source URL: ${input.sourceUrl}. Remix goal: ${input.remixGoal}.`,
        idea_angle: `${input.marketSignal} in ${setting}`,
        idea_formula: `${input.themeCluster} + ${input.niche} + ${setting} + ${swap}`,
        remix_strategy: `Pattern kept: audience curiosity and transformation. Changed: setting, characters, rival, visual scene and payoff.`,
        score,
      },
      input,
      index
    );
  });
}

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as RemixInput;

    const input: Required<RemixInput> = {
      storyPillar: cleanText(body.storyPillar, "Story"),
      themeCluster: cleanText(body.themeCluster, "Poor vs Rich"),
      niche: cleanText(body.niche, "Poor vs Rich vs Giga Rich"),
      marketSignal: cleanText(body.marketSignal, "Huntrix Fashion Contest"),
      sourceTitle: cleanText(body.sourceTitle, "Unknown Source Video"),
      sourceDescription: cleanText(body.sourceDescription, ""),
      sourceChannel: cleanText(body.sourceChannel, "Unknown Channel"),
      sourceUrl: cleanText(body.sourceUrl, ""),
      remixGoal: cleanText(
        body.remixGoal,
        "Create an original YouTube story idea using the source only as a market signal."
      ),
      remixRule: cleanText(
        body.remixRule,
        "Keep market logic. Change characters, setting, conflict, twist, thumbnail scene and payoff."
      ),
      targetAudience: cleanText(body.targetAudience, "US kids and family audience"),
      visualStyle: cleanText(
        body.visualStyle,
        "bright contrast, transformation, expressive faces"
      ),
      language: cleanText(body.language, "EN"),
      ideaCount: clampCount(body.ideaCount),
    };

    const mockMode = process.env.OPENAI_MOCK_MODE === "true";
    const apiKey = process.env.OPENAI_API_KEY;

    if (mockMode || !apiKey) {
      return NextResponse.json({
        mode: "mock",
        warning: mockMode
          ? "Mock mode is on."
          : "No OpenAI API key found. Returned mock remix ideas.",
        ideas: buildMockIdeas(input),
      });
    }

    try {
      const openai = new OpenAI({
        apiKey,
      });

      const model = process.env.OPENAI_MODEL || "gpt-4o-mini";

      const response = await openai.chat.completions.create({
        model,
        response_format: {
          type: "json_object",
        },
        messages: [
          {
            role: "system",
            content:
              "You are StudioOS Remix Rule Engine V2. You transform competitor/source signals into original YouTube story ideas. Never copy titles, thumbnails, characters, wording, scenes, or story beats. Output valid JSON only.",
          },
          {
            role: "user",
            content: JSON.stringify({
              task: "Generate original remix ideas from source signal.",
              required_json_shape: {
                ideas: [
                  {
                    title: "string",
                    theme: "string",
                    hook: "string",
                    thumbnail_prompt: "string",
                    storyline: "string",
                    notes: "string",
                    score: "number",
                    story_pillar: "string",
                    theme_cluster: "string",
                    niche: "string",
                    idea_angle: "string",
                    idea_formula: "string",
                    source_signal: "string",
                    priority_level: "Focus | Test | Backlog",
                    remix_rule: "string",
                    remix_strategy: "string",
                  },
                ],
              },
              remix_rules: [
                "Do not copy the source title.",
                "Do not copy the source thumbnail.",
                "Do not copy the source storyline.",
                "Extract only the market logic: theme, contrast, emotion, payoff, curiosity.",
                "Change characters, setting, conflict, twist, thumbnail scene and ending.",
                "Follow this taxonomy: Story Pillar → Theme Cluster → Niche → Specific Idea.",
                "Make titles specific and clickable.",
              ],
              input,
            }),
          },
        ],
      });

      const content = response.choices[0]?.message?.content || "{}";
      const parsed = JSON.parse(content) as {
        ideas?: Partial<RemixIdea>[];
      };

      const ideas = (parsed.ideas || [])
        .slice(0, input.ideaCount)
        .map((idea, index) => normalizeIdea(idea, input, index));

      if (ideas.length === 0) {
        return NextResponse.json({
          mode: "fallback",
          warning: "OpenAI returned no usable ideas. Returned mock ideas.",
          ideas: buildMockIdeas(input),
        });
      }

      return NextResponse.json({
        mode: "openai",
        ideas,
      });
    } catch (error) {
      return NextResponse.json({
        mode: "fallback",
        warning:
          error instanceof Error
            ? error.message
            : "OpenAI remix failed. Returned mock remix ideas.",
        ideas: buildMockIdeas(input),
      });
    }
  } catch (error) {
    return NextResponse.json(
      {
        error:
          error instanceof Error
            ? error.message
            : "Invalid remix request.",
      },
      {
        status: 400,
      }
    );
  }
}
